In [15]:
from scipy import optimize
import numpy as np

def f_grad(x, *args):
    x_0, x_1 = args
    return np.array([2 * (x[0] - x_0), 2* (x[1] - x_1)])

def f(x, *args):
    x_0, x_1 = args
    return (x[0] - x_0)**2 + (x[1] - x_1)**2
bounds = ((0, np.inf), (0, np.inf))

test = optimize.fmin_l_bfgs_b(f, np.array([0, 0]), args = (3,2), fprime =  f_grad, bounds=bounds  )

In [6]:
import numpy as np
N_num = 10
x = np.arange(N_num)
y = np.arange(N_num)
xx, yy = np.meshgrid(x,y)

In [7]:
test = xx + yy
print( test )

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]
